// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workflow.proto

package face_authenticator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnrollStatus int32

const (
	EnrollStatus_ENROLL_STATUS_OK    EnrollStatus = 0
	EnrollStatus_ENROLL_STATUS_ERROR EnrollStatus = 1
)

var EnrollStatus_name = map[int32]string{
	0: "ENROLL_STATUS_OK",
	1: "ENROLL_STATUS_ERROR",
}

var EnrollStatus_value = map[string]int32{
	"ENROLL_STATUS_OK":    0,
	"ENROLL_STATUS_ERROR": 1,
}

func (x EnrollStatus) String() string {
	return proto.EnumName(EnrollStatus_name, int32(x))
}

func (EnrollStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}

type AuthenticateStatus int32

const (
	AuthenticateStatus_AUTHENTICATE_STATUS_OK    AuthenticateStatus = 0
	AuthenticateStatus_AUTHENTICATE_STATUS_ERROR AuthenticateStatus = 1
)

var AuthenticateStatus_name = map[int32]string{
	0: "AUTHENTICATE_STATUS_OK",
	1: "AUTHENTICATE_STATUS_ERROR",
}

var AuthenticateStatus_value = map[string]int32{
	"AUTHENTICATE_STATUS_OK":    0,
	"AUTHENTICATE_STATUS_ERROR": 1,
}

func (x AuthenticateStatus) String() string {
	return proto.EnumName(AuthenticateStatus_name, int32(x))
}

func (AuthenticateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}

type Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type FaceCoordinates struct {
	TopLeft              *Point   `protobuf:"bytes,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	BottomRight          *Point   `protobuf:"bytes,2,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"`
	LeftEye              *Point   `protobuf:"bytes,3,opt,name=left_eye,json=leftEye,proto3" json:"left_eye,omitempty"`
	RightEye             *Point   `protobuf:"bytes,4,opt,name=right_eye,json=rightEye,proto3" json:"right_eye,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceCoordinates) Reset()         { *m = FaceCoordinates{} }
func (m *FaceCoordinates) String() string { return proto.CompactTextString(m) }
func (*FaceCoordinates) ProtoMessage()    {}
func (*FaceCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}

func (m *FaceCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceCoordinates.Unmarshal(m, b)
}
func (m *FaceCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceCoordinates.Marshal(b, m, deterministic)
}
func (m *FaceCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceCoordinates.Merge(m, src)
}
func (m *FaceCoordinates) XXX_Size() int {
	return xxx_messageInfo_FaceCoordinates.Size(m)
}
func (m *FaceCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_FaceCoordinates proto.InternalMessageInfo

func (m *FaceCoordinates) GetTopLeft() *Point {
	if m != nil {
		return m.TopLeft
	}
	return nil
}

func (m *FaceCoordinates) GetBottomRight() *Point {
	if m != nil {
		return m.BottomRight
	}
	return nil
}

func (m *FaceCoordinates) GetLeftEye() *Point {
	if m != nil {
		return m.LeftEye
	}
	return nil
}

func (m *FaceCoordinates) GetRightEye() *Point {
	if m != nil {
		return m.RightEye
	}
	return nil
}

type FaceRequest struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Face                 []byte           `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	FaceCoordinates      *FaceCoordinates `protobuf:"bytes,3,opt,name=face_coordinates,json=faceCoordinates,proto3" json:"face_coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FaceRequest) Reset()         { *m = FaceRequest{} }
func (m *FaceRequest) String() string { return proto.CompactTextString(m) }
func (*FaceRequest) ProtoMessage()    {}
func (*FaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{2}
}

func (m *FaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceRequest.Unmarshal(m, b)
}
func (m *FaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceRequest.Marshal(b, m, deterministic)
}
func (m *FaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceRequest.Merge(m, src)
}
func (m *FaceRequest) XXX_Size() int {
	return xxx_messageInfo_FaceRequest.Size(m)
}
func (m *FaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaceRequest proto.InternalMessageInfo

func (m *FaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FaceRequest) GetFace() []byte {
	if m != nil {
		return m.Face
	}
	return nil
}

func (m *FaceRequest) GetFaceCoordinates() *FaceCoordinates {
	if m != nil {
		return m.FaceCoordinates
	}
	return nil
}

type EnrollRequest struct {
	FaceRequest          *FaceRequest `protobuf:"bytes,1,opt,name=face_request,json=faceRequest,proto3" json:"face_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnrollRequest) Reset()         { *m = EnrollRequest{} }
func (m *EnrollRequest) String() string { return proto.CompactTextString(m) }
func (*EnrollRequest) ProtoMessage()    {}
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{3}
}

func (m *EnrollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollRequest.Unmarshal(m, b)
}
func (m *EnrollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollRequest.Marshal(b, m, deterministic)
}
func (m *EnrollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollRequest.Merge(m, src)
}
func (m *EnrollRequest) XXX_Size() int {
	return xxx_messageInfo_EnrollRequest.Size(m)
}
func (m *EnrollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollRequest proto.InternalMessageInfo

func (m *EnrollRequest) GetFaceRequest() *FaceRequest {
	if m != nil {
		return m.FaceRequest
	}
	return nil
}

type EnrollResponse struct {
	Status               EnrollStatus `protobuf:"varint,1,opt,name=status,proto3,enum=face_authenticator.EnrollStatus" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnrollResponse) Reset()         { *m = EnrollResponse{} }
func (m *EnrollResponse) String() string { return proto.CompactTextString(m) }
func (*EnrollResponse) ProtoMessage()    {}
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{4}
}

func (m *EnrollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollResponse.Unmarshal(m, b)
}
func (m *EnrollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollResponse.Marshal(b, m, deterministic)
}
func (m *EnrollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollResponse.Merge(m, src)
}
func (m *EnrollResponse) XXX_Size() int {
	return xxx_messageInfo_EnrollResponse.Size(m)
}
func (m *EnrollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollResponse proto.InternalMessageInfo

func (m *EnrollResponse) GetStatus() EnrollStatus {
	if m != nil {
		return m.Status
	}
	return EnrollStatus_ENROLL_STATUS_OK
}

func (m *EnrollResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthenticateRequest struct {
	FaceRequest          *FaceRequest `protobuf:"bytes,1,opt,name=face_request,json=faceRequest,proto3" json:"face_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{5}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetFaceRequest() *FaceRequest {
	if m != nil {
		return m.FaceRequest
	}
	return nil
}

type AuthenticateResponse struct {
	Status               AuthenticateStatus `protobuf:"varint,1,opt,name=status,proto3,enum=face_authenticator.AuthenticateStatus" json:"status,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{6}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetStatus() AuthenticateStatus {
	if m != nil {
		return m.Status
	}
	return AuthenticateStatus_AUTHENTICATE_STATUS_OK
}

func (m *AuthenticateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("face_authenticator.EnrollStatus", EnrollStatus_name, EnrollStatus_value)
	proto.RegisterEnum("face_authenticator.AuthenticateStatus", AuthenticateStatus_name, AuthenticateStatus_value)
	proto.RegisterType((*Point)(nil), "face_authenticator.Point")
	proto.RegisterType((*FaceCoordinates)(nil), "face_authenticator.FaceCoordinates")
	proto.RegisterType((*FaceRequest)(nil), "face_authenticator.FaceRequest")
	proto.RegisterType((*EnrollRequest)(nil), "face_authenticator.EnrollRequest")
	proto.RegisterType((*EnrollResponse)(nil), "face_authenticator.EnrollResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "face_authenticator.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "face_authenticator.AuthenticateResponse")
}

func init() {
	proto.RegisterFile("workflow.proto", fileDescriptor_892c7f566756b0be)
}

var fileDescriptor_892c7f566756b0be = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x6f, 0xd2, 0x50,
	0x18, 0xc6, 0xd7, 0x6d, 0x32, 0x78, 0xe9, 0x18, 0x79, 0xb7, 0x28, 0x5b, 0x62, 0x9c, 0x5d, 0xa2,
	0xcb, 0x12, 0x99, 0x41, 0x63, 0xbc, 0x50, 0x93, 0xb2, 0xd4, 0x3f, 0x91, 0x80, 0x1e, 0xba, 0x0b,
	0x4d, 0x4c, 0x53, 0xca, 0x29, 0x34, 0x96, 0x1e, 0x3c, 0x3d, 0xcd, 0xd6, 0x4b, 0x3f, 0xb3, 0x5f,
	0xc0, 0xf6, 0xb4, 0x0d, 0x30, 0xd8, 0xf0, 0xc2, 0xbb, 0xf3, 0x1e, 0x9e, 0xe7, 0xf7, 0x9c, 0xe7,
	0x25, 0x29, 0xd4, 0xae, 0x18, 0xff, 0xe9, 0xfa, 0xec, 0xaa, 0x39, 0xe5, 0x4c, 0x30, 0x44, 0xd7,
	0x76, 0xa8, 0x65, 0x47, 0x62, 0x4c, 0x03, 0xe1, 0x39, 0xb6, 0x60, 0x5c, 0x3b, 0x81, 0x7b, 0x5f,
	0x98, 0x17, 0x08, 0x54, 0x41, 0xb9, 0x6e, 0x28, 0xc7, 0xca, 0xe9, 0x16, 0x51, 0xae, 0xd3, 0x29,
	0x6e, 0x6c, 0x66, 0x53, 0xac, 0xfd, 0x51, 0x60, 0xef, 0x7d, 0xe2, 0xbd, 0x60, 0x8c, 0x0f, 0xbd,
	0xc0, 0x16, 0x34, 0xc4, 0x97, 0x50, 0x16, 0x6c, 0x6a, 0xf9, 0xd4, 0x15, 0xd2, 0x56, 0x6d, 0x1d,
	0x36, 0x97, 0xf9, 0x4d, 0x09, 0x27, 0x3b, 0x89, 0xb4, 0x93, 0x28, 0xf1, 0x0d, 0xa8, 0x03, 0x26,
	0x04, 0x9b, 0x58, 0xdc, 0x1b, 0x8d, 0x85, 0x8c, 0xb8, 0xd3, 0x59, 0xcd, 0xe4, 0x24, 0x55, 0xa7,
	0x99, 0x69, 0x9e, 0x45, 0x63, 0xda, 0xd8, 0x5a, 0x9b, 0x99, 0x4a, 0x8d, 0x98, 0xe2, 0x2b, 0xa8,
	0xc8, 0x30, 0x69, 0xdb, 0x5e, 0x67, 0x2b, 0x4b, 0x6d, 0xe2, 0xd3, 0x7e, 0x2b, 0x50, 0x4d, 0x5b,
	0x13, 0xfa, 0x2b, 0xa2, 0xa1, 0xc0, 0x1a, 0x6c, 0x7a, 0x43, 0xd9, 0xb5, 0x42, 0x92, 0x13, 0x22,
	0x6c, 0xa7, 0x14, 0xd9, 0x41, 0x25, 0xf2, 0x8c, 0x5d, 0xa8, 0x4b, 0xb2, 0x33, 0xdb, 0x54, 0xfe,
	0xd2, 0x93, 0x55, 0x91, 0x37, 0x96, 0x4a, 0xf6, 0xdc, 0xc5, 0x0b, 0xad, 0x0f, 0xbb, 0x46, 0xc0,
	0x99, 0xef, 0x17, 0x8f, 0x68, 0x83, 0x2a, 0x39, 0x3c, 0x9b, 0xf3, 0xd5, 0x3f, 0xba, 0x0d, 0x9e,
	0xdb, 0x48, 0xd5, 0x9d, 0x0d, 0xda, 0x10, 0x6a, 0x05, 0x34, 0x9c, 0xb2, 0x20, 0xa4, 0xf8, 0x1a,
	0x4a, 0xa1, 0xb0, 0x45, 0x14, 0x4a, 0x5e, 0xad, 0x75, 0xbc, 0x8a, 0x97, 0x79, 0xfa, 0x52, 0x47,
	0x72, 0x3d, 0x36, 0x60, 0x67, 0x42, 0xc3, 0xd0, 0x1e, 0x65, 0x7b, 0xa8, 0x90, 0x62, 0xd4, 0xbe,
	0xc1, 0xbe, 0x3e, 0xf3, 0xd3, 0xff, 0x59, 0x60, 0x0a, 0x07, 0x8b, 0xe8, 0xbc, 0xc6, 0xbb, 0x1b,
	0x35, 0x9e, 0xac, 0xa2, 0xce, 0x3b, 0xff, 0xb5, 0xcc, 0xd9, 0x5b, 0x50, 0xe7, 0xeb, 0xe3, 0x01,
	0xd4, 0x8d, 0x2e, 0xe9, 0x75, 0x3a, 0x56, 0xdf, 0xd4, 0xcd, 0xcb, 0xbe, 0xd5, 0xfb, 0x5c, 0xdf,
	0xc0, 0x07, 0xb0, 0xbf, 0x78, 0x6b, 0x10, 0xd2, 0x23, 0x75, 0xe5, 0xac, 0x07, 0xb8, 0x1c, 0x8b,
	0x47, 0x70, 0x5f, 0xbf, 0x34, 0x3f, 0x1a, 0x5d, 0xf3, 0xd3, 0x85, 0x6e, 0x1a, 0x0b, 0xa8, 0x87,
	0x70, 0xb8, 0xea, 0xb7, 0x1c, 0xd8, 0xfa, 0x01, 0xe5, 0xec, 0x3d, 0x94, 0xe3, 0x57, 0x28, 0x51,
	0x79, 0xc6, 0xc7, 0xb7, 0xff, 0x6d, 0xf9, 0xea, 0x8e, 0xb4, 0xbb, 0x24, 0xd9, 0x1a, 0xb5, 0x8d,
	0x96, 0x80, 0x5d, 0x7d, 0x5e, 0x81, 0x0e, 0xa8, 0x73, 0x16, 0x8a, 0x4f, 0xd7, 0x6d, 0xb6, 0xc8,
	0x3b, 0x5d, 0x2f, 0x2c, 0x52, 0xdb, 0xcf, 0xbf, 0x37, 0x47, 0x9e, 0x18, 0x47, 0x83, 0xa6, 0xc3,
	0x26, 0xe7, 0x1f, 0x22, 0xcf, 0xf7, 0xed, 0x68, 0x42, 0x9f, 0xb5, 0x59, 0x24, 0x78, 0x7c, 0xbe,
	0x0c, 0x1a, 0x94, 0xe4, 0x87, 0xed, 0xc5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0x15, 0x0b,
	0xc7, 0xea, 0x04, 0x00, 0x00,
}
